- name: Testing Ansible in os
  debug:
    msg:
      - Hello from  {{ ansible_distribution }} {{ ansible_distribution_version }}
      - Hostname is {{ ansible_hostname }}


- include_tasks: debian/install.yml

- name: Configuring fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    force: no
    validate: '/usr/bin/fail2ban-client -d -f %s'
  notify: restart fail2ban
