---
# tasks file for jinopl.fail2ban
- name: Run when os is redhat family
  include: rhel.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Run when os Debian family
  include: debian.yml
  when: ansible_facts['os_family'] == "Debian"


- name: Adding local conf to configuration
  template:
    src: jail.local
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban



