- name: Testing Ansible in os
  debug:
    msg:
      - Hello from  {{ ansible_distribution }} {{ ansible_distribution_version }}
      - Hostname is {{ ansible_hostname }}

- include: rhel/install.yml

- name: Configuring fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    force: no
  notify: restart fail2ban